Using device serial when using adb.
The Android device serial number, specified by the --device-serial
command-line option, was unused by the android_webview wptrunner.
This resulted in adb failing with the following error:

    adb wait-for-device
    error: more than one device/emulator

Bug: None
Change-Id: I85e236297d7e83950ac26a9283bdad4ef642d62c